version: '3.3'

services:
    db:
        image: mysql:5.7
        volumes:
            - db:/var/lib/mysql
        ports:
            - '3306:3306'
        #restart: always
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: testdb
            MYSQL_USER: tyrone
            MYSQL_PASSWORD: tyrone

    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        volumes:
            - php:/usr/local/etc/php/conf.d
            - ./site:/var/www/html
        ports:
            - '8080:80'
        #restart: always
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: tyrone
            WORDPRESS_DB_PASSWORD: tyrone
            WORDPRESS_DB_NAME: testdb

volumes:
    db:
    php:
